# Site settings
title: Hossein Karami | حسین کرمی
email: hi@hosseinkarami.com
description: توسعه‌دهنده رابط کاربری
baseurl: "http://mrashedi.ir/"
url: "http://mrashedi.ir"
twitter: _Karamii
github:  HosseinKarami
behance: HosseinKarami
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]
